export const callesPorLocalidad = {
    "Barker": [
        "2 DE ABRIL",
        "A STORNI",
        "ALMAFUERTE",
        "ALTE BROWN",
        "AV ARGENTINA",
        "AV FORTABAT",
        "BIS KUPAL",
        "BIS NAMUNCURA",
        "BIS NEWEN",
        "BIS RUCAWEN",
        "BOLIVIA",
        "BRASIL",
        "C C VIGIL",
        "CANADA",
        "CATAMARCA",
        "CERRITO",
        "CHACO",
        "CHILE",
        "CN M DORREGO",
        "COLOMBIA",
        "CORDOBA",
        "COSTA RICA",
        "CUBA",
        "DE LA VIRGEN",
        "DIAGONAL 25 DE MAYO",
        "DR ROJAS",
        "DR. B. JUAREZ",
        "ECUADOR",
        "ENTRE RIOS",
        "FORMOSA",
        "G MISTRAL",
        "G ORDAS",
        "GEORGIAS DEL SUR",
        "GRAL BELGRANO",
        "GRAL MOSCONI",
        "GRAL SAVIO",
        "GRAL. J. DE SAN MARTIN",
        "GUATEMALA",
        "GUAYANA",
        "H WATS",
        "HAITI",
        "HERNANDEZ",
        "HONDURAS",
        "ISLAS MALVINAS",
        "J INGENIEROS",
        "J NEWBERY",
        "JAMAICA",
        "JUJUY",
        "LA RIOJA",
        "M ROLDAN",
        "MACHADO",
        "MEXICO",
        "NICARAGUA",
        "NTRA SRA DEL CARMEN",
        "ORCADAS DEL SUR",
        "OTAMENDI",
        "P ESPETXE",
        "PANAMA",
        "PARAGUAY",
        "PERU",
        "PTE ALLENDE",
        "PTE. DR. IRIGOYEN",
        "PTE. SARMIENTO",
        "PUERTO ARGENTINO",
        "PUERTO RICO",
        "R FALCON",
        "R FINOCHETO",
        "R GUIRALDES",
        "REP. DE BAHAMAS",
        "REP. DOMINICANA",
        "RUTA PROVINCIAL N 80",
        "SALTA",
        "SAN JUAN",
        "SAN LUIS",
        "SANTA FE",
        "SANTIAGO DEL ESTERO",
        "TRINIDAD Y TOBAGO",
        "TUCUMAN",
        "URUGUAY",
        "VENEZUELA",
        "VUCETICH",
        "VUELTA DE OBLIGADO",
        "WEICHA"
    ],
    "Benito Juarez": [
        "1ERO DE MAYO",
        "25 DE MAYO",
        "3 DE JULIO",
        "9 DE JULIO",
        "ACOSTA NU",
        "ALMAFUERTE",
        "ALMIRANTE BROWN",
        "ALVARO BARROS",
        "ANDRES GIUNTA",
        "ANTARTIDA ARGENTINA",
        "AV ACTIS CAPORALE",
        "AV OTAMENDI",
        "AV TAGLIORETTI",
        "Av. A. STORNI",
        "Av. ALSINA",
        "Av. B. MITRE",
        "Av. CONSTITUCION",
        "Av. CORONEL M. DORREGO",
        "Av. DOLORES BLANCO",
        "Av. FORTABAT",
        "Av. HUMAITA",
        "Av. J. B. ALBERDI",
        "Av. J.M. MUNIZ",
        "Av. JOSE ARTIGAS",
        "Av. JUAN M. DE ROSAS",
        "Av. LIBERTAD",
        "Av. M. DE UNAMUNO",
        "Av. PTE PERON",
        "Av. R. O. DEL URUGUAY",
        "Av. R. S. PENA",
        "Av. SAAVEDRA",
        "Av. SALENAVE",
        "Av. SAN MARTIN",
        "Av. URQUIZA",
        "Av. ZABALZA",
        "AYACUCHO",
        "B. GUGLIELMETTI",
        "B. TORRES",
        "Bis COSTARRICA",
        "Bis HONDURAS",
        "Bis SAINTOUT",
        "BLANDENQUES",
        "BOLIVIA",
        "BOUCHARD",
        "BRASIL",
        "C. ZIBECCHI",
        "CAMINO DEL BICENTENARIO",
        "CAPITAN RAMOS",
        "CARLOS GARDEL",
        "CATAMARCA",
        "CHACABUCO",
        "CHACO",
        "CHILAVERT",
        "COLOMBIA",
        "CORDOBA",
        "CORRIENTES",
        "CUBA",
        "D. F. SARMIENTO",
        "DE LOS INMIGRANTES",
        "DEL FEDERALISMO",
        "DR LABRIOLA",
        "DR. T. MUNOZ",
        "DR. VICTOR RIGANTI",
        "ECUADOR",
        "EVA PERON",
        "FALUCHO",
        "FLORENTINO AMEGUINO",
        "GARABAGLIA",
        "GARDEL",
        "GRAL GUEMES",
        "GRAL LAS HERAS",
        "GRAL LAVALLE",
        "GRAL. M. BELGRANO",
        "GRAL. PAZ",
        "GRAL. RODRIGUEZ",
        "GUARDIA NACIONAL",
        "H. IRIGOYEN",
        "HOMERO MANZI",
        "ICASTO",
        "INT J.C.MORTATI",
        "ISLAS MALVINAS",
        "ITUZAINGO",
        "J. B. JUSTO",
        "J. MARTI",
        "J.C.PORCEL DE PERALTA",
        "JAMAICA",
        "JAURETCHE",
        "JOSE HERNANDEZ",
        "JUJUY",
        "L. N. ALEM",
        "LA RIOJA",
        "LAPRIDA",
        "LAS ACACIAS",
        "LAS CASUARINAS",
        "LEUVUCO",
        "LISANDRO DE LA TORRE",
        "LOS AGUARIBAYS",
        "LOS CEDROS",
        "LOS EUCALIPTOS",
        "LOS ROBLES",
        "LUIS JOSE PAVIA",
        "M. CERVANTES",
        "MAIPU",
        "MANSILLA",
        "MAR DEL PLATA",
        "MARIANO MORENO",
        "MARIANO ROLDAN",
        "MARIO QUIÑONES",
        "MARTIN FIERRO",
        "MENDOZA",
        "MEXICO",
        "MISIONES",
        "N. AVELLANEDA",
        "O.URBINA",
        "PADRE OSVALDO CATENA",
        "PALACIOS",
        "PANAMA",
        "PASAJE CHE GUEVARA",
        "PASAJE DE LOS MUSICOS",
        "PASAJE PERALTA",
        "PASAJE SALA CARRILLO",
        "PELLEGRINI",
        "PENALOZA",
        "PERITO F. MORENO",
        "PUMARA",
        "REP. DE CHILE",
        "REP. DEL PERU",
        "RIVADAVIA",
        "RUBEN DARIO",
        "SALINAS GRANDES",
        "SAN ANTONIO",
        "SAN JUAN",
        "SGO. DEL ESTERO",
        "STO. CABRAL",
        "SUIPACHA",
        "TUCUMAN",
        "VELEZ SARDIELD",
        "VUELTA DE OBLIGADO",
        "YATASTO"
    ],
    "Estacion Lopez": [
        "ABEL CAMPOAMOR",
        "ALEJANDRO ANDERSEN",
        "BERNARDO FERNANDEZ",
        "EDUARDO DUHALDE",
        "EMA EANDI DE GIRADO",
        "GERÓNIMO SANTILLÁN",
        "JOSE BUSTOS",
        "JOSE VIDAL",
        "LOS PINOS",
        "LUIS MAGNANINI",
        "MONICA AGUILERA",
        "REGINALDO DE CASTRO",
        "ROBERTO GIRADO",
        "TOMASA TAPIA DE BUSTOS"
    ],
    "Tedin Uriburu": [
        "1ERA COMISION MUNICIPAL",
        "ALBERTO ELHAIEK",
        "ANGEL SALMERON",
        "BELGRANO",
        "CALLE 9",
        "CONSTANCIO VIGIL",
        "DAVID PRIETO",
        "HUGO SBALBI",
        "I IRIGOYEN",
        "MARIA D GOLIA",
        "MARIANO ROLDAN",
        "MITRE",
        "RAUL GARAVAGLIA",
        "RIVADAVIA",
        "ROCA",
        "SARMIENTO",
        "TORIBIO TALADRIZ"
    ]
};