export const callesPorLocalidad = {
    "Barker": [
        "A. Storni",
        "Almafuerte",
        "Av. Antartida Argentina",
        "Av. Fortabat",
        "C.C. Vigil",
        "Cerrito",
        "De la Virgen",
        "G. Mistral",
        "G. Ordas",
        "Gral. Mosconi",
        "Gral. Savio",
        "H. Wats",
        "Islas Malvinas",
        "J. Ingenieros",
        "J. Newbery",
        "M. Roldán",
        "Machado",
        "Ntra. Sra. del Carmen",
        "Otamendi",
        "P. Espetxe",
        "R. Falcón",
        "R. Finochetto",
        "R. Güiraldes",
        "Vucetich"
    ],
    "Villa Cacique": [
        "2 de Abril",
        "Alte Brown",
        "Bis Kupal",
        "Bis Namuncurá",
        "Bis Newen",
        "Bis Rucawen",
        "Bolivia",
        "Brasil",
        "Canadá",
        "Catamarca",
        "Chaco",
        "Chile",
        "Cn M. Dorrego",
        "Colombia",
        "Córdoba",
        "Costa Rica",
        "Cuba",
        "Diagonal 25 de Mayo",
        "Dr. Rojas",
        "Dr. B. Juárez",
        "Ecuador",
        "Entre Ríos",
        "Formosa",
        "Georgias del Sur",
        "Gral Belgrano",
        "Gral J. de San Martín",
        "Guatemala",
        "Guayana",
        "Haití",
        "Hernández",
        "Honduras",
        "Islas Malvinas",
        "Jamaica",
        "Jujuy",
        "La Rioja",
        "México",
        "Nicaragua",
        "Orcadas del Sur",
        "Panamá",
        "Paraguay",
        "Perú",
        "Pte. Allende",
        "Pte. Dr. Irigoyen",
        "Pte. Sarmiento",
        "Puerto Argentino",
        "Puerto Rico",
        "Rep. de Bahamas",
        "Rep. Dominicana",
        "Ruta Provincial N° 80",
        "Salta",
        "San Juan",
        "San Luis",
        "Santa Fe",
        "Santiago del Estero",
        "Trinidad y Tobago",
        "Tucumán",
        "Uruguay",
        "Venezuela",
        "Vuelta de Obligado",
        "Weicha"
    ],
    "Benito Juarez": [
        "1º de Mayo",
        "25 de Mayo",
        "3 de Julio",
        "9 de Julio",
        "Acosta Ñu",
        "Almafuerte",
        "Almirante Brown",
        "Álvaro Barros",
        "Andrés Giunta",
        "Antártida Argentina",
        "Av. Actis Caporale",
        "Av. Otamendi",
        "Av. Taglioretti",
        "Av. A. Storni",
        "Av. Alsina",
        "Av. B. Mitre",
        "Av. Constitución",
        "Av. Coronel M. Dorrego",
        "Av. Dolores Blanco",
        "Av. Fortabat",
        "Av. Humaitá",
        "Av. J. B. Alberdi",
        "Av. J. M. Muñiz",
        "Av. José Artigas",
        "Av. Juan M. de Rosas",
        "Av. Libertad",
        "Av. M. de Unamuno",
        "Av. Pte. Perón",
        "Av. R. O. del Uruguay",
        "Av. R. S. Peña",
        "Av. Saavedra",
        "Av. Salenave",
        "Av. San Martín",
        "Av. Urquiza",
        "Av. Zabalza",
        "Ayacucho",
        "B. Guglielmetti",
        "B. Torres",
        "Bis Costa Rica",
        "Bis Honduras",
        "Bis Saintout",
        "Blandenques",
        "Bolivia",
        "Bouchard",
        "Brasil",
        "C. Zibecchi",
        "Cabo Egañez",
        "Camino del Bicentenario",
        "Capitán Ramos",
        "Carlos Gardel",
        "Catamarca",
        "Chacabuco",
        "Chaco",
        "Chilavert",
        "Colombia",
        "Córdoba",
        "Corrientes",
        "Cuba",
        "D. F. Sarmiento",
        "De la Torre",
        "De los Inmigrantes",
        "Del Federalismo",
        "Dr. Labriola",
        "Dr. Taglioretti",
        "Dr. T. Muñoz",
        "Dr. Víctor Riganti",
        "Ecuador",
        "Eva Perón",
        "Falucho",
        "Florentino Ameghino",
        "Garabaglia",
        "Gardel",
        "Gral. Güemes",
        "Gral. Las Heras",
        "Gral. Lavalle",
        "Gral. M. Belgrano",
        "Gral. Paz",
        "Gral. Rodríguez",
        "Guardia Nacional",
        "H. Irigoyen",
        "Homero Manzi",
        "Icasto",
        "Int. J. C. Mortati",
        "Islas Malvinas",
        "Ituzaingó",
        "J. B. Justo",
        "J. Martí",
        "J. C. Porcel de Peralta",
        "Jamaica",
        "Jauretche",
        "José Hernández",
        "Jujuy",
        "L. N. Alem",
        "La Rioja",
        "Laprida",
        "Las Acacias",
        "Las Casuarinas",
        "Leuvuco",
        "Lisandro de la Torre",
        "Los Aguaribays",
        "Los Cedros",
        "Los Eucaliptos",
        "Los Robles",
        "Luis José Pavía",
        "M. Cervantes",
        "Maipú",
        "Mansilla",
        "Mar del Plata",
        "Mariano Moreno",
        "Mariano Roldán",
        "Mario Quiñones",
        "Martín Fierro",
        "Mendoza",
        "México",
        "Misiones",
        "N. Avellaneda",
        "O. Urbina",
        "Padre Osvaldo Catena",
        "Palacios",
        "Panamá",
        "Pasaje Che Guevara",
        "Pasaje de los Músicos",
        "Pasaje Peralta",
        "Pasaje Sala Carrillo",
        "Pellegrini",
        "Peñaloza",
        "Perito F. Moreno",
        "Pumará",
        "Rep. de Chile",
        "Rep. del Perú",
        "Rivadavia",
        "Rubén Darío",
        "Salinas Grandes",
        "San Antonio",
        "San Juan",
        "Sgo. del Estero",
        "Sto. Cabral",
        "Suipacha",
        "Tucumán",
        "Vélez Sarsfield",
        "Vuelta de Obligado",
        "Yatasto"
    ],
    "Estacion Lopez": [
        "Abel Campoamor",
        "Alejandro Andersen",
        "Bernardo Fernandez",
        "Eduardo Duhalde",
        "Ema Eandi de Girado",
        "Gerónimo Santillán",
        "Jose Bustos",
        "Jose Vidal",
        "Los Pinos",
        "Luis Magnanini",
        "Monica Aguilera",
        "Reginaldo de Castro",
        "Roberto Girado",
        "Tomasa Tapia de Bustos"
    ],
    "Tedin Uriburu": [
        [
            "1era Comisión Municipal",
            "Alberto Elhaiek",
            "Ángel Salmerón",
            "Belgrano",
            "Calle 9",
            "Constancio Vigil",
            "David Prieto",
            "Hugo Sbalbi",
            "I. Irigoyen",
            "María D. Golia",
            "Mariano Roldán",
            "Mitre",
            "Raúl Garavaglia",
            "Rivadavia",
            "Roca",
            "Sarmiento",
            "Toribio Taladriz"
        ]
    ]
};