export enum Nacionalidad {
    ARGENTINA = 'ARGENTINA',
    BOLIVIANA = 'BOLIVIANA',
    CHILENA = 'CHILENA',
    PARAGUAYA = 'PARAGUAYA',
    URUGUAYA = 'URUGUAYA',
    PERUANA = 'PERUANA',
    BRASILEÑA = 'BRASILEÑA',
    VENEZOLANA = 'VENEZOLANA',
    COLOMBIANA = 'COLOMBIANA',
    ESPAÑOLA = 'ESPAÑOLA',
    ITALIANA = 'ITALIANA',
    CHINA = 'CHINA',
    JAPONESA = 'JAPONESA',
    COREANA = 'COREANA',
    SIRIA = 'SIRIA',
    LIBANESA = 'LIBANESA',
    OTRO = 'OTRO'
}

